### ISSUE TITLE
Clickonce

### ISSUE THREAD

**Issue by timluyten** [Jaben/Papercut#16]
Hi,

Although clickonce is a nice way to distribute, our firewalls are blocking these requests, so I can't install the tool.

Is there also a standalone version I can download somewhere?

Tim

**Comment by Jaben** [comment]
Yes. Releases are avaliable here: https://github.com/Jaben/Papercut/releases

"Copy deployment" works well with Papercut. Simply unzip the Papercut.4.x.x.x.zip file into a directory and run.
