### ISSUE TITLE
Long URLs are cut when browser is opened

### ISSUE THREAD

**Issue by enkelmedia** [Jaben/Papercut#2]
Also here:
https://papercut.codeplex.com/workitem/9878

I have emails with links that are very long, like this: 

<a href="http://Tasdf.com/app/pages/tracking/trackclick.aspx?nid=101105002158069113090238180025171086185053047158&e=026132148126184225126027168024182076173041160248017135148071116092102090209215142169163147093251&url=http%3a%2f%2fns2.dev.yada%2fpages%2ftracking%2funsubscribe.aspx%3fe%3d026132148126184225126027168024182076173041160248017135148071116092102090209215142169163147093251%26sb%3dProvider_10%26nid%3d101105002158069113090238180025171086185053047158%26utm_medium%3demail%26utm_content%3dHellop%26utm_campaign%3dagain">Unsubscribe</a> 

If I look at the body of the email in Papercut the links looks ok but when I click the link and it opens in the browser, the only part that is opened looks like this: 

http://http://WHAT.com/app/pages/tracking/unsubscribe.aspx?e=051105028069171139049167184077109087244202003253242201060154088016015172077075124115194217187202 

So for some reason papercut cuts of a major part of the url - is it only me or is this an issue that can be reproduced?

**Comment by Jaben** [comment]
Please attach the EML file with the issue.

**Comment by enkelmedia** [comment]
Hi! 

Can't attach EML files, but you can find it here: https://www.dropbox.com/s/8heykiso4ck389x/2015090318010268-8399.eml?dl=0

**Comment by Jaben** [comment]
Thanks.

Yeah, I can't reproduce. When I click the link, the browser url in Chrome matches. Maybe a sneaky/buggy extension or worse some sort of "listener" on your system? Have you tried on any other computer

**Comment by enkelmedia** [comment]
Hi!

I always recomment Papercut to use with my email plugin for Umbraco CMS so it was one of my clients who found the bug. Opeing this file in Outlook works great. I'm on Windows 10 with Microsoft Edge if that might have any impact?
