### ISSUE TITLE
Stop working on windows 7

### ISSUE THREAD

**Issue by nadeendra** [Jaben/Papercut#26]
I download and installed papercut on windows 7 VM. When I try to run it, it stop working and give following error

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	papercut.exe
  Problem Signature 02:	4.5.0.0
  Problem Signature 03:	56b0189a
  Problem Signature 04:	Autofac
  Problem Signature 05:	3.5.0.0
  Problem Signature 06:	53ea13f4
  Problem Signature 07:	282
  Problem Signature 08:	85
  Problem Signature 09:	System.IO.FileLoadException
  OS Version:	6.1.7600.2.0.0.256.4
  Locale ID:	1033
  Additional Information 1:	3a14
  Additional Information 2:	3a141e763fcddd6f6f1ff62b2b1b61ff
  Additional Information 3:	75ea
  Additional Information 4:	75ea500045a5a896f6f4ca0c98fa8b2d

**Comment by Jaben** [comment]
Did you try running it with admin permissions?

**Comment by nadeendra** [comment]
Yes !
I was using a domain account may be that's the issue
domain account is also part of the local admin group btw

**Comment by Jaben** [comment]
k, glad it's working. The error handling could be improved, though.
