### ISSUE TITLE
Offline Installation

### ISSUE THREAD

**Issue by maffmommie** [Jaben/Papercut#27]
I'm a complete novice.  Just wondering how I can run this on a Windows server that doesn't have an internet connection.

**Comment by Jaben** [comment]
Yes. Go to the releases: https://github.com/Jaben/Papercut/releases

Get the latest zip of Papercut (e.g. _**Papercut.4.6.1.12.zip**_ as of writing) -- unzip and run!

**Comment by maffmommie** [comment]
Thanks, Jaben!
