### ISSUE TITLE
Starting Papercut

### ISSUE THREAD

**Issue by maffmommie** [Jaben/Papercut#28]
Ok...maybe I'm not doing something right.

To start Papercut, you have to start the service (run Install-Papercut-Service.bat) then run the Papercut.exe.  I have done that but the command prompt is stopped at 
`"Server Ready - listening for New Connections 127.0.0.1":37403`

No icons are appearing.  Nothing is showing in the notification window.

Is there something that I'm missing?

**Comment by Jaben** [comment]
Yeah, you don't need the service. Unzip Papercut.zip and run Papercut.exe using admin permissions or in a folder that you have full write permissions.

The Papercut App is not a command-line app -- so you should see the standard GUI come up.
